# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec5cf3c88684b6b636020b78d845f04e8e41394e12030e0e78d1ec46a0ffbd3bd33ff42ca6eadb766dc1eacc33803c16d7e9cad63bc85ae5c97af560334a5452

test:
  secret_key_base: c33b77d203d87fedf3b21021c44b6a354049b0a301d1ce8c4fdc8fe7f517bbda1ccc7ae4d27c2c3bdcb8ec7b0bca59ca3cd5e89acec888085ade5573626eb08c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
